WEB/NawamMa/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "NawamMa"

urlpatterns = [
    path("", views.layout, name='home'),
    path("mypage/", views.mypage, name='mypage'),

    #만든이 소개
    path('maker/', views.maker , name ='maker'),
    path('extend/', views.extend , name ='extend'),
    #출발/목적지 입력
    path('start/', views.start, name = 'start'),
    path('startP/', views.startP, name = 'startP'),
    #지하철 혼잡도
    path('subway/', views.subway, name = 'subway'),
    path('subwayP/', views.subwayP, name = 'subwayP'),
    #좌석관련
    path('seat/<int:number>/', views.seat , name ='seat'),
    path('preRequset/', views.preRequset , name ='preRequset'),
    path('seatP/<int:number>/', views.seatP , name ='seatP'),
    path('MseatP/', views.MseatP, name = 'MseatP'),
    path('Mseat/', views.Mseat, name = 'Mseat'),
]

WEB/board/urls.py
from django.urls import path
from . import views

app_name = "board"

urlpatterns = [
    path("boardlist/", views.boardlist, name='boardlist'),
    path('create/', views.create, name='create'),
    path('newboard/', views.boardform, name='newboard'),
    path('edit/<int:pk>', views.edit, name='edit'),
    path('remove/<int:pk>', views.remove, name='remove'),
    path('detail/<int:pk>', views.detail, name='detail'),
    path('detail/<int:board_id>/<int:comment_id>', views.comment_delete, name='comment_delete'),
    ##모바일뷰
    path('Mboard/', views.Mboard , name ='Mboard'),
]

WEB/member/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "member"

urlpatterns = [
    path('login/', views.login , name ='login'),
    path('logout/', views.logout , name ='logout'),
    path('register/', views.register , name ='register'),
]

WEB/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("NawamMa.urls")),  #기존기능
    path('board/', include("board.urls")), #게시판
    path('member/', include("member.urls")), #기존로그인
    path('accounts/', include('allauth.urls')), #소셜로그인
    ]
    
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WEB/templates/extend.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="/static/assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="/static/assets/img/logo.png">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    NawaMma
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no'
    name='viewport' />
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css"
    href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- CSS Files -->
  <link href="/static/assets/css/material-kit.css?v=2.0.5" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="/static/assets/demo/demo.css" rel="stylesheet" />
  <style>
    @font-face {
      font-family: 'SeoulNamsanM';
      src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_two@1.0/SeoulNamsanM.woff') format('woff');
      font-weight: normal;
      font-style: normal;
    }

    .font {
      font-family: 'SeoulNamsanM';
    }

    .material-icons1 {
      font-size: 100px;
      display: inline-block;
      padding: 20px;
      align: center;
    }
  </style>
</head>

<body class="index-page sidebar-collapse font">
  <div class="background" style="background-color: rgb(50, 0, 50);">
    {% block nav %}
    <nav class="navbar navbar-transparent navbar-expand-lg bg-primary" color-on-scroll="100" id="sectionsNav">
      <div class="container">
        <div class="navbar-translate">
          <img src="/static/assets/img/logo.png" alt="logo" class="rounded-circle img-fluid" width="55px" height="55px">
          <a class="navbar-brand" href="{% url 'NawamMa:home' %}">
            나왐마 </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon"></span>
            <span class="navbar-toggler-icon"></span>
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="navbar-nav ml-auto">
            <li class="dropdown nav-item">
              <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                <i class="material-icons">subway</i> 자리검색
              </a>
              <div class="dropdown-menu dropdown-with-icons">
                <a href="{% url 'NawamMa:start' %}" class="dropdown-item">
                  <i class="material-icons">accessibility_new</i> 일반 자리검색
                </a>
                <a href="{% url 'NawamMa:startP' %}" class="dropdown-item">
                  <i class="material-icons">pregnant_woman</i> 임산부 자리검색
                </a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'board:boardlist' %}" onclick="scrollToDownload()">
                <i class="material-icons">desktop_mac</i> 게시판
              </a>
            </li>
            <li class="dropdown nav-item">
              <a href="#pablo" class="profile-photo dropdown-toggle nav-link" data-toggle="dropdown">
                <div class="profile-photo-small">
                  <img src="/static/assets/img/hyunsoo.png" alt="Circle Image" class="rounded-circle img-fluid">
                </div>
              </a>
              <div class="dropdown-menu dropdown-menu-right">
                <h6 class="dropdown-header font">MYPAGE</h6>
                {% if user.is_authenticated %}
                <a href="{% url 'NawamMa:mypage' %}" class="dropdown-item">{{user.nickname}}</a>
                <a href="{% url 'member:logout' %}" class="dropdown-item">로그아웃</a>
                {% else %}
                <a href="{% url 'member:login' %}" class="dropdown-item">로그인</a>
                <a href="{% url 'member:register' %}" class="dropdown-item">회원가입</a>
                {% endif %}
                <a href="{% url 'NawamMa:maker' %}" class="dropdown-item">만든이</a>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <br>
    <br>

    {% endblock %}
    {% block main %}
    <div class="main main-raised">
      <div class="section" id="carousel">
        <div class="container">
          <div class="row">
            <div class="col-md-12 mr-auto ml-auto">
              <!-- Carousel Card -->
              <div class="card card-raised card-carousel">
                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" data-interval="3000">
                  <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                  </ol>
                  <div class="carousel-inner">
                    <div class="carousel-item active">
                      <img class="d-block w-100" src="/static/assets/img/serviceInfo/service1.JPG" alt="1 slide">
                    </div>
                    <div class="carousel-item">
                      <img class="d-block w-100" src="/static/assets/img/serviceInfo/service2.JPG" alt="2 slide">
                    </div>
                    <div class="carousel-item">
                      <img class="d-block w-100" src="/static/assets/img/serviceInfo/service3.JPG" alt="3 slide">
                    </div>
                    <div class="carousel-item">
                      <img class="d-block w-100" src="/static/assets/img/serviceInfo/service4.JPG" alt="4 slide">
                    </div>
                    <div class="carousel-item">
                      <img class="d-block w-100" src="/static/assets/img/serviceInfo/service5.JPG" alt="5 slide">
                    </div>
                    <div class="carousel-item">
                      <img class="d-block w-100" src="/static/assets/img/serviceInfo/service6.JPG" alt="6 slide">
                    </div>
                    <div class="carousel-item">
                      <img class="d-block w-100" src="/static/assets/img/serviceInfo/service7.JPG" alt="7 slide">
                    </div>
                    <div class="carousel-item">
                      <img class="d-block w-100" src="/static/assets/img/serviceInfo/service8.JPG" alt="8 slide">
                    </div>
                    <div class="carousel-item">
                      <img class="d-block w-100" src="/static/assets/img/serviceInfo/service9.JPG" alt="9 slide">
                    </div>
                  </div>
                  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <i class="material-icons">keyboard_arrow_left</i>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <i class="material-icons">keyboard_arrow_right</i>
                    <span class="sr-only">Next</span>
                  </a>
                </div>
              </div>
              <!-- End Carousel Card -->
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endblock %}
    {% block footer %}
    <footer class="footer" style="color: white;">
      <div class="container">
        <div class="copyright float-left">
          <ul>
            <li>
              Team
            </li>
            <li>
              <a href="https://github.com/">
                김예진
              </a>
            </li>
            <li>
              <a href="https://github.com/koreakevin/">
                이광현
              </a>
            </li>
            <li>
              <a href="https://github.com/HamJinKyoung/">
                함진경
              </a>
            </li>
            <li>
              <a href="https://github.com/">
                김현수
              </a>
            </li>
          </ul>

        </div>
        <div class="copyright float-right">
          &copy;
          <script>
            document.write(new Date().getFullYear())
          </script>, made with <i class="material-icons">favorite</i> by Likelion 7th x SKHU<img
            src="/static/assets/img/skhulogo.png" width="55px" height="55px">
        </div>
      </div>
    </footer>
    {% endblock %}
  </div>
  <!--         end carousel -->


  <!--   Core JS Files   -->
  <script src="/static/assets/js/core/jquery.min.js" type="text/javascript"></script>
  <script src="/static/assets/js/core/popper.min.js" type="text/javascript"></script>
  <script src="/static/assets/js/core/bootstrap-material-design.min.js" type="text/javascript"></script>
  <script src="/static/assets/js/plugins/moment.min.js"></script>

  <!--	Plugin for the Datepicker, full documentation here: https://github.com/Eonasdan/bootstrap-datetimepicker -->
  <script src="/static/assets/js/plugins/bootstrap-datetimepicker.js" type="text/javascript"></script>

  <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
  <script src="/static/assets/js/plugins/nouislider.min.js" type="text/javascript"></script>

  <!-- Control Center for Material Kit: parallax effects, scripts for the example pages etc -->
  <script src="/static/assets/js/material-kit.js?v=2.0.5" type="text/javascript"></script>

  {% block javascript %}

  <script>
    $(document).ready(function () {
      //init DateTimePickers
      materialKit.initFormExtendedDatetimepickers();

      // Sliders Init
      materialKit.initSliders();
    });


    function scrollToDownload() {
      if ($('.section-download').length != 0) {
        $("html, body").animate({
          scrollTop: $('.section-download').offset().top
        }, 1000);
      }
    }
  </script>
  {% endblock %}
</body>

</html>

WEB/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="static/assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="static/assets/img/favicon.png">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    NawamMa
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no'
    name='viewport' />
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css"
    href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- CSS Files -->
  <link href="static/assets/css/material-kit.css?v=2.0.5" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="static/assets/demo/demo.css" rel="stylesheet" />
  <style>
    @font-face {
      font-family: 'SeoulNamsanM';
      src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_two@1.0/SeoulNamsanM.woff') format('woff');
      font-weight: normal;
      font-style: normal;
    }

    .font {
      font-family: 'SeoulNamsanM';
    }
  </style>
</head>

<body class="offline-doc font">
  <nav class="navbar navbar-transparent navbar-color-on-scroll fixed-top navbar-expand-lg bg-primary"
    color-on-scroll="100" id="sectionsNav">
    <div class="container">
      <div class="navbar-translate">
        <img src="/static/assets/img/logo.png" alt="logo" class="rounded-circle img-fluid" width="55px" height="55px">
        <a class="navbar-brand" href="{% url 'NawamMa:home' %}">
          NawamMa </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false"
          aria-label="Toggle navigation">
          <span class="sr-only">Toggle navigation</span>
          <span class="navbar-toggler-icon"></span>
          <span class="navbar-toggler-icon"></span>
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto">
          <li class="dropdown nav-item">
            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
              <i class="material-icons">subway</i> 자리검색
            </a>
            <div class="dropdown-menu dropdown-with-icons">
              <a href="{% url 'NawamMa:start' %}" class="dropdown-item">
                <i class="material-icons">accessibility_new</i> 일반 자리검색
              </a>
              <a href="{% url 'NawamMa:startP' %}" class="dropdown-item">
                <i class="material-icons">pregnant_woman</i> 임산부 자리검색
              </a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'board:boardlist' %}" onclick="scrollToDownload()">
              <i class="material-icons">desktop_mac</i> 게시판
            </a>
          </li>
          <li class="dropdown nav-item">
            <a href="#pablo" class="profile-photo dropdown-toggle nav-link" data-toggle="dropdown">
              <div class="profile-photo-small">
                <img src="/static/assets/img/hyunsoo.png" alt="Circle Image" class="rounded-circle img-fluid">
              </div>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
              <h6 style="font-family: 'SeoulNamsanM';" class="dropdown-header">MYPAGE</h6>
              {% if user.is_authenticated %}
              <a href="{% url 'NawamMa:mypage' %}" class="dropdown-item">{{ user.nickname }}</a>
              <a href="{% url 'member:logout' %}" class="dropdown-item">로그아웃</a>
              {% else %}
              <a href="{% url 'member:login' %}" class="dropdown-item">로그인</a>
              <a href="{% url 'member:register' %}" class="dropdown-item">회원가입</a>
              {% endif %}
              <a href="{% url 'NawamMa:maker' %}" class="dropdown-item">만든이</a>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="page-header header-filter" data-parallax="true"
    style="background-image: url('static/assets/img/header.jpg')">
    <div class="container">
      <div class="row">
        <div class="col-md-6 ml-auto mr-auto">
          <div class="brand text-center">
            <h1 style="font-family: 'SeoulNamsanM';"><b>나왐마!</b></h1>
            <h4 style="font-family: 'SeoulNamsanM';">"더이상 눈치보지 마세요, 이제 나왐마를 보세요."</h4>
            <br>
            <a href="{% url 'NawamMa:maker' %}" target="_blank" class="btn btn-primary btn-raised btn-lg">
              <i class="fa fa-play"></i> About Us
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <footer class="footer">
    <div class="container">
      <div class="copyright float-left">
        <ul>
          <li>
            Team
          </li>
          <li>
            <a href="https://github.com/">
              김예진
            </a>
          </li>
          <li>
            <a href="https://github.com/koreakevin/">
              이광현
            </a>
          </li>
          <li>
            <a href="https://github.com/HamJinKyoung/">
              함진경
            </a>
          </li>
          <li>
            <a href="https://github.com/khs9628/">
              김현수
            </a>
          </li>
        </ul>

      </div>
      <div class="copyright float-right">
        &copy;
        <script>
          document.write(new Date().getFullYear())
        </script>, made with <i class="material-icons">favorite</i> by Likelion 7th x SKHU<img
          src="/static/assets/img/skhulogo.png" width="55px" height="55px">
      </div>
    </div>
  </footer>
  <!--   Core JS Files   -->
  <script src="static/assets/js/core/jquery.min.js" type="text/javascript"></script>
  <script src="static/assets/js/core/popper.min.js" type="text/javascript"></script>
  <script src="static/assets/js/core/bootstrap-material-design.min.js" type="text/javascript"></script>
  <script src="static/assets/js/plugins/moment.min.js"></script>
  <!--	Plugin for the Datepicker, full documentation here: https://github.com/Eonasdan/bootstrap-datetimepicker -->
  <script src="static/assets/js/plugins/bootstrap-datetimepicker.js" type="text/javascript"></script>
  <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
  <script src="static/assets/js/plugins/nouislider.min.js" type="text/javascript"></script>
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
  <!-- Control Center for Material Kit: parallax effects, scripts for the example pages etc -->
  <script src="static/assets/js/material-kit.js?v=2.0.5" type="text/javascript"></script>
</body>

</html>

WEB/templates/profile-page.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="/static/assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="/static/assets/img/favicon.png">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    Material Kit by Creative Tim
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- CSS Files -->
  <link href="/static/assets/css/material-kit.css?v=2.0.5" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="/static/assets/demo/demo.css" rel="stylesheet" />
</head>

<body class="profile-page sidebar-collapse">
  <nav class="navbar navbar-transparent navbar-color-on-scroll fixed-top navbar-expand-lg" color-on-scroll="100" id="sectionsNav">
    <div class="container">
      <div class="navbar-translate">
        <a class="navbar-brand" href="https://demos.creative-tim.com/material-kit/index.html">
          Material Kit </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="sr-only">Toggle navigation</span>
          <span class="navbar-toggler-icon"></span>
          <span class="navbar-toggler-icon"></span>
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto">
          <li class="dropdown nav-item">
            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
              <i class="material-icons">apps</i> Components
            </a>
            <div class="dropdown-menu dropdown-with-icons">
              <a href="/static/index.html" class="dropdown-item">
                <i class="material-icons">layers</i> All Components
              </a>
              <a href="https://demos.creative-tim.com/material-kit/docs/2.1/getting-started/introduction.html" class="dropdown-item">
                <i class="material-icons">content_paste</i> Documentation
              </a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="javascript:void(0)" onclick="scrollToDownload()">
              <i class="material-icons">cloud_download</i> Download
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" rel="tooltip" title="" data-placement="bottom" href="https://twitter.com/CreativeTim" target="_blank" data-original-title="Follow us on Twitter">
              <i class="fa fa-twitter"></i>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" rel="tooltip" title="" data-placement="bottom" href="https://www.facebook.com/CreativeTim" target="_blank" data-original-title="Like us on Facebook">
              <i class="fa fa-facebook-square"></i>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" rel="tooltip" title="" data-placement="bottom" href="https://www.instagram.com/CreativeTimOfficial" target="_blank" data-original-title="Follow us on Instagram">
              <i class="fa fa-instagram"></i>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="page-header header-filter" data-parallax="true" style="background-image: url('/static/assets/img/city-profile.jpg');"></div>
  <div class="main main-raised">
    <div class="profile-content">
      <div class="container">
        <div class="row">
          <div class="col-md-6 ml-auto mr-auto">
            <div class="profile">
              <div class="avatar">
                <img src="/static/assets/img/faces/christian.jpg" alt="Circle Image" class="img-raised rounded-circle img-fluid">
              </div>
              <div class="name">
                <h3 class="title">Christian Louboutin</h3>
                <h6>Designer</h6>
                <a href="#pablo" class="btn btn-just-icon btn-link btn-dribbble"><i class="fa fa-dribbble"></i></a>
                <a href="#pablo" class="btn btn-just-icon btn-link btn-twitter"><i class="fa fa-twitter"></i></a>
                <a href="#pablo" class="btn btn-just-icon btn-link btn-pinterest"><i class="fa fa-pinterest"></i></a>
              </div>
            </div>
          </div>
        </div>
        <div class="description text-center">
          <p>An artist of considerable range, Chet Faker &#x2014; the name taken by Melbourne-raised, Brooklyn-based Nick Murphy &#x2014; writes, performs and records all of his own music, giving it a warm, intimate feel with a solid groove structure. </p>
        </div>
        <div class="row">
          <div class="col-md-6 ml-auto mr-auto">
            <div class="profile-tabs">
              <ul class="nav nav-pills nav-pills-icons justify-content-center" role="tablist">
                <li class="nav-item">
                  <a class="nav-link active" href="#studio" role="tab" data-toggle="tab">
                    <i class="material-icons">camera</i> Studio
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#works" role="tab" data-toggle="tab">
                    <i class="material-icons">palette</i> Work
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#favorite" role="tab" data-toggle="tab">
                    <i class="material-icons">favorite</i> Favorite
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="tab-content tab-space">
          <div class="tab-pane active text-center gallery" id="studio">
            <div class="row">
              <div class="col-md-3 ml-auto">
                <img src="/static/assets/img/examples/studio-1.jpg" class="rounded">
                <img src="/static/assets/img/examples/studio-2.jpg" class="rounded">
              </div>
              <div class="col-md-3 mr-auto">
                <img src="/static/assets/img/examples/studio-5.jpg" class="rounded">
                <img src="/static/assets/img/examples/studio-4.jpg" class="rounded">
              </div>
            </div>
          </div>
          <div class="tab-pane text-center gallery" id="works">
            <div class="row">
              <div class="col-md-3 ml-auto">
                <img src="/static/assets/img/examples/olu-eletu.jpg" class="rounded">
                <img src="/static/assets/img/examples/clem-onojeghuo.jpg" class="rounded">
                <img src="/static/assets/img/examples/cynthia-del-rio.jpg" class="rounded">
              </div>
              <div class="col-md-3 mr-auto">
                <img src="/static/assets/img/examples/mariya-georgieva.jpg" class="rounded">
                <img src="/static/assets/img/examples/clem-onojegaw.jpg" class="rounded">
              </div>
            </div>
          </div>
          <div class="tab-pane text-center gallery" id="favorite">
            <div class="row">
              <div class="col-md-3 ml-auto">
                <img src="/static/assets/img/examples/mariya-georgieva.jpg" class="rounded">
                <img src="/static/assets/img/examples/studio-3.jpg" class="rounded">
              </div>
              <div class="col-md-3 mr-auto">
                <img src="/static/assets/img/examples/clem-onojeghuo.jpg" class="rounded">
                <img src="/static/assets/img/examples/olu-eletu.jpg" class="rounded">
                <img src="/static/assets/img/examples/studio-1.jpg" class="rounded">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <footer class="footer footer-default">
    <div class="container">
      <nav class="float-left">
        <ul>
          <li>
            <a href="https://www.creative-tim.com">
              Creative Tim
            </a>
          </li>
          <li>
            <a href="https://creative-tim.com/presentation">
              About Us
            </a>
          </li>
          <li>
            <a href="http://blog.creative-tim.com">
              Blog
            </a>
          </li>
          <li>
            <a href="https://www.creative-tim.com/license">
              Licenses
            </a>
          </li>
        </ul>
      </nav>
      <div class="copyright float-right">
        &copy;
        <script>
          document.write(new Date().getFullYear())
        </script>, made with <i class="material-icons">favorite</i> by
        <a href="https://www.creative-tim.com" target="_blank">Creative Tim</a> for a better web.
      </div>
    </div>
  </footer>
  <!--   Core JS Files   -->
  <script src="/static/assets/js/core/jquery.min.js" type="text/javascript"></script>
  <script src="/static/assets/js/core/popper.min.js" type="text/javascript"></script>
  <script src="/static/assets/js/core/bootstrap-material-design.min.js" type="text/javascript"></script>
  <script src="/static/assets/js/plugins/moment.min.js"></script>

  <!--	Plugin for the Datepicker, full documentation here: https://github.com/Eonasdan/bootstrap-datetimepicker -->
  <script src="/static/assets/js/plugins/bootstrap-datetimepicker.js" type="text/javascript"></script>

  <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
  <script src="/static/assets/js/plugins/nouislider.min.js" type="text/javascript"></script>

  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
  
  <!-- Control Center for Material Kit: parallax effects, scripts for the example pages etc -->
  <script src="/static/assets/js/material-kit.js?v=2.0.5" type="text/javascript"></script>
</body>

</html>