WEB/board/urls.py
from django.urls import path
from . import views

app_name = "board"

urlpatterns = [
    path("boardlist/", views.boardlist, name='boardlist'),
    path('create/', views.create, name='create'),
    path('newboard/', views.boardform, name='newboard'),
    path('edit/<int:pk>', views.edit, name='edit'),
    path('remove/<int:pk>', views.remove, name='remove'),
    path('detail/<int:pk>', views.detail, name='detail'),
    path('detail/<int:board_id>/<int:comment_id>', views.comment_delete, name='comment_delete'),
    ##모바일뷰
    path('Mboard/', views.Mboard , name ='Mboard'),
]

WEB/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("NawamMa.urls")),  #기존기능
    path('board/', include("board.urls")), #게시판
    path('member/', include("member.urls")), #기존로그인
    path('accounts/', include('allauth.urls')), #소셜로그인
    ]
    
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WEB/board/models.py
from django.db import models

# Create your models here.
class Board(models.Model):
    title = models.CharField(max_length=200)
    writer = models.CharField(max_length=200)
    content = models.TextField()
    date = models.DateTimeField('date published')
    # 공지사항 / 자유게시판 -> I / F
    stat_choices = (('I','공지사항'), ('F','자유게시판'))
    stat = models.CharField(max_length=10, choices=stat_choices)
    hashtags = models.ManyToManyField('Hashtag', blank=True)
    image = models.ImageField(upload_to='board/image/', blank=True)
    

    def __str__(self):
        return self.title
    
    def summary(self):
        return self.content[:30]

class Hashtag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Comment(models.Model):
    Board_pk = models.ForeignKey(Board, on_delete=models.CASCADE, related_name ="comments")
    comment_text = models.CharField(max_length=50)
    c_date = models.DateTimeField('date published')

    def __str__(self):
        return self.comment_text

WEB/board/forms.py
from django import forms
from .models import Board, Comment

class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ['title', 'content', 'stat', 'hashtags', 'image']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["comment_text"]

WEB/board/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .forms import BoardForm , CommentForm
from .models import Board, Hashtag, Comment

# Create your views here.

### 게시판관련
def boardlist(request):
        boards = Board.objects
        return render(request, 'board/boardlist.html', {'boards':boards})

def create(request):
    board = Board()
    board.title = request.GET['title']
    board.writer = request.GET['writer']
    board.content = request.GET['content']
    board.stat = request.GET['stat']
    board.hashtags = request.GET['hashtags']
    board.image = request.GET['image']
    board.date = timezone.datetime.now()
    board.save()
    return redirect('board:boardlist')

def boardform(request, board=None):
        user = request.user.nickname
        if request.method == 'POST':
                form = BoardForm(request.POST, request.FILES, instance=board)
                if form.is_valid():
                        board = form.save(commit=False)
                        board.title = form.cleaned_data['title']
                        board.writer = user
                        board.content = form.cleaned_data['content']
                        board.stat = form.cleaned_data['stat']
                        board.date = timezone.now()
                        board.save()
                        form.save_m2m()
                        return redirect('board:boardlist')
        else:
                form = BoardForm(instance=board)
                return render(request, 'board/new.html', {'form':form})

def edit(request, pk):
        board = get_object_or_404(Board, pk=pk)
        return boardform(request, board)

def remove(request, pk):
        board = get_object_or_404(Board, pk=pk)
        board.delete()
        return redirect('board:boardlist')


def detail(request, pk):
        board = get_object_or_404(Board, pk=pk)
        if request .method == "POST":
                form = CommentForm(request .POST)
                if form.is_valid():
                        comment = form.save(commit=False)
                        comment.Board_pk= board
                        comment.comment_text = form.cleaned_data["comment_text"]
                        comment.c_date = timezone.now()
                        comment.save()
                        return redirect('board:detail', pk)
        else:
                form = CommentForm()
                return render(request, 'board/detail.html', {'form':form,'board':board})

def comment_delete(request, board_id, comment_id):
        comment = get_object_or_404(Comment, pk=comment_id)
        comment.delete()
        return redirect('board:detail',board_id)
##모바일 관련
def Mboard(request):
        return render(request, 'board/Mboardlist.html')

WEB/board/templates/board/Mboardlist.html
{% extends 'extend.html' %}
{% load staticfiles %}

<!-- IMPORT Table css -->
{% block css %}
<link href="/static/assets/js/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
{% endblock %}

{% block main %}
<div class="main main-raised">
  <div class="section">
    <div class="container">
      <div id="navigation-pills">
        <div class="row">
          <div class="col-lg-6 col-md-8">
            <ul class="nav nav-pills nav-pills-primary nav-pills-icons" role="tablist">
              <li class="nav-item">
                <a class="nav-link active" href="#dashboard-1" role="tab" data-toggle="tab">
                  <i class="material-icons">dashboard</i> 공지사항
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#schedule-1" role="tab" data-toggle="tab">
                  <i class="material-icons">schedule</i> 자유게시판
                </a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'board:newboard' %}">
                  <i class="material-icons">create</i> 글쓰기
                </a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </div>

      <div class="tab-content tab-space">
        <!-- 공지사항 -->
        <div class="tab-pane active" id="dashboard-1">
          <div class="row">
            <div class="col-md-12 mr-auto ml-auto">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>번호</th>
                      <th>제목</th>
                      <th>내용</th>
                      <th>날짜</th>
                      <th>수정</th>
                      <th>삭제</th>
                    </tr>
                  </thead>
                  <!-- <tfoot>
                    <tr>
                      <th>번호</th>
                      <th>제목</th>
                      <th>내용</th>
                      <th>날짜</th>
                      <th>수정</th>
                      <th>삭제</th>
                    </tr>
                  </tfoot> -->
                  <tbody>
                    {% for board in boards.all %}
                    {% if board.stat == "I" %}
                    <tr>
                      <td>{{ board.id }}</td>
                      <td>
                        {% for hashtag in board.hashtags.all %}
                        {{ hashtag.name }}
                        {% endfor %}
                        {{ board.title }}</td>
                      <td>{{ board.summary }}<a href="{% url 'board:detail' pk=board.pk %}">...</a></td>
                      <td>{{ board.date }}</td>
                      {% if board.writer == user.nickname %}
                      <td style="text-align:center">
                        <a href="{% url 'board:edit' pk=board.pk %}" class="btn btn-success btn-circle">
                          <i class="fa fa-check"></i>
                        </a>
                      </td>
                      <td style="text-align:center">
                        <a href="{% url 'board:remove' pk=board.pk %}" class="btn btn-danger btn-circle">
                          <i class="fa fa-trash"></i>
                        </a>
                      </td>
                      {% else %}
                      <td style="text-align:center">
                        <a href="{% url 'board:edit' pk=board.pk %}" class="btn btn-success btn-circle disabled">
                          <i class="fa fa-check"></i>
                        </a>
                      </td>
                      <td style="text-align:center">
                        <a href="{% url 'board:remove' pk=board.pk %}" class="btn btn-danger btn-circle disabled">
                          <i class="fa fa-trash"></i>
                        </a>
                      </td>
                      {% endif %}
                    </tr>
                    {% endif %}
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
        <!-- 자유게시판 -->
        <div class="tab-pane" id="schedule-1">
          <div class="row">
            <div class="col-md-12 mr-auto ml-auto">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable1" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>번호</th>
                      <th>제목</th>
                      <th>내용</th>
                      <th>날짜</th>
                      <th>수정</th>
                      <th>삭제</th>
                    </tr>
                  </thead>
                  <!-- <tfoot>
                    <tr>
                      <th>글번호</th>
                      <th>제목</th>
                      <th>내용</th>
                      <th>날짜</th>
                      <th>수정</th>
                      <th>삭제</th>
                    </tr>
                  </tfoot> -->
                  <tbody>
                    {% for board in boards.all %}
                    {% if board.stat == "F" %}
                    <tr>
                      <td>{{ board.id }}</td>
                      <td>
                        {% for hashtag in board.hashtags.all %}
                        {{ hashtag.name }}
                        {% endfor %}
                        {{ board.title }}</td>
                      <td>{{ board.summary }}<a href="{% url 'board:detail' pk=board.pk %}">...</a></td>
                      <td>{{ board.date }}</td>
                      {% if board.writer == user.nickname %}
                      <td style="text-align:center">
                        <a href="{% url 'board:edit' pk=board.pk %}" class="btn btn-success btn-circle">
                          <i class="fa fa-check"></i>
                        </a>
                      </td>
                      <td style="text-align:center">
                        <a href="{% url 'board:remove' pk=board.pk %}" class="btn btn-danger btn-circle">
                          <i class="fa fa-trash"></i>
                        </a>
                      </td>
                      {% else %}
                      <td style="text-align:center">
                        <a href="{% url 'board:edit' pk=board.pk %}" class="btn btn-success btn-circle disabled">
                          <i class="fa fa-check"></i>
                        </a>
                      </td>
                      <td style="text-align:center">
                        <a href="{% url 'board:remove' pk=board.pk %}" class="btn btn-danger btn-circle disabled">
                          <i class="fa fa-trash"></i>
                        </a>
                      </td>
                      {% endif %}
                    </tr>
                    {% endif %}
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}



<!-- IMPORT Table JS -->
{% block javascript %}
<script src="/static/assets/js/datatables/jquery.dataTables.min.js"></script>
<script src="/static/assets/js/datatables/dataTables.bootstrap4.min.js"></script>
<script src="/static/assets/js/datatables/dataTables.responsive.js"></script>
<script>
  $(document).ready(function () {
    $('#dataTable').DataTable({
      responsive: true
    });
  });

  $(document).ready(function () {
    $('#dataTable1').DataTable({
      responsive: true
    });
  });
</script>
{% endblock %}

WEB/board/templates/board/boardlist.html
{% extends 'extend.html' %}
{% load staticfiles %}

<!-- IMPORT Table css -->
{% block css %}
<link href="/static/assets/js/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
{% endblock %}

{% block main %}
<div class="main main-raised">
  <div class="section">
    <div class="container">
      <div id="navigation-pills">
        <div class="row">
          <div class="col-lg-6 col-md-8">
            <ul class="nav nav-pills nav-pills-primary nav-pills-icons" role="tablist">
              <li class="nav-item">
                <a class="nav-link active" href="#dashboard-1" role="tab" data-toggle="tab">
                  <i class="material-icons">dashboard</i> 공지사항
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#schedule-1" role="tab" data-toggle="tab">
                  <i class="material-icons">schedule</i> 자유게시판
                </a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'board:newboard' %}">
                  <i class="material-icons">create</i> 글쓰기
                </a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </div>

      <div class="tab-content tab-space">
        <!-- 공지사항 -->
        <div class="tab-pane active" id="dashboard-1">
          <div class="row">
            <div class="col-md-12 mr-auto ml-auto">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>번호</th>
                      <th>제목</th>
                      <th>내용</th>
                      <th>날짜</th>
                      <th>수정</th>
                      <th>삭제</th>
                    </tr>
                  </thead>
                  <!-- <tfoot>
                    <tr>
                      <th>번호</th>
                      <th>제목</th>
                      <th>내용</th>
                      <th>날짜</th>
                      <th>수정</th>
                      <th>삭제</th>
                    </tr>
                  </tfoot> -->
                  <tbody>
                    {% for board in boards.all %}
                    {% if board.stat == "I" %}
                    <tr>
                      <td>{{ board.id }}</td>
                      <td>
                        {% for hashtag in board.hashtags.all %}
                        {{ hashtag.name }}
                        {% endfor %}
                        {{ board.title }}</td>
                      <td>{{ board.summary }}<a href="{% url 'board:detail' pk=board.pk %}">...</a></td>
                      <td>{{ board.date }}</td>
                      {% if board.writer == user.nickname %}
                      <td style="text-align:center">
                        <a href="{% url 'board:edit' pk=board.pk %}" class="btn btn-success btn-circle">
                          <i class="fa fa-check"></i>
                        </a>
                      </td>
                      <td style="text-align:center">
                        <a href="{% url 'board:remove' pk=board.pk %}" class="btn btn-danger btn-circle">
                          <i class="fa fa-trash"></i>
                        </a>
                      </td>
                      {% else %}
                      <td style="text-align:center">
                        <a href="{% url 'board:edit' pk=board.pk %}" class="btn btn-success btn-circle disabled">
                          <i class="fa fa-check"></i>
                        </a>
                      </td>
                      <td style="text-align:center">
                        <a href="{% url 'board:remove' pk=board.pk %}" class="btn btn-danger btn-circle disabled">
                          <i class="fa fa-trash"></i>
                        </a>
                      </td>
                      {% endif %}
                    </tr>
                    {% endif %}
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
        <!-- 자유게시판 -->
        <div class="tab-pane" id="schedule-1">
          <div class="row">
            <div class="col-md-12 mr-auto ml-auto">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable1" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>번호</th>
                      <th>제목</th>
                      <th>내용</th>
                      <th>날짜</th>
                      <th>수정</th>
                      <th>삭제</th>
                    </tr>
                  </thead>
                  <!-- <tfoot>
                    <tr>
                      <th>글번호</th>
                      <th>제목</th>
                      <th>내용</th>
                      <th>날짜</th>
                      <th>수정</th>
                      <th>삭제</th>
                    </tr>
                  </tfoot> -->
                  <tbody>
                    {% for board in boards.all %}
                    {% if board.stat == "F" %}
                    <tr>
                      <td>{{ board.id }}</td>
                      <td>
                        {% for hashtag in board.hashtags.all %}
                        {{ hashtag.name }}
                        {% endfor %}
                        {{ board.title }}</td>
                      <td>{{ board.summary }}<a href="{% url 'board:detail' pk=board.pk %}">...</a></td>
                      <td>{{ board.date }}</td>
                      {% if board.writer == user.nickname %}
                      <td style="text-align:center">
                        <a href="{% url 'board:edit' pk=board.pk %}" class="btn btn-success btn-circle">
                          <i class="fa fa-check"></i>
                        </a>
                      </td>
                      <td style="text-align:center">
                        <a href="{% url 'board:remove' pk=board.pk %}" class="btn btn-danger btn-circle">
                          <i class="fa fa-trash"></i>
                        </a>
                      </td>
                      {% else %}
                      <td style="text-align:center">
                        <a href="{% url 'board:edit' pk=board.pk %}" class="btn btn-success btn-circle disabled">
                          <i class="fa fa-check"></i>
                        </a>
                      </td>
                      <td style="text-align:center">
                        <a href="{% url 'board:remove' pk=board.pk %}" class="btn btn-danger btn-circle disabled">
                          <i class="fa fa-trash"></i>
                        </a>
                      </td>
                      {% endif %}
                    </tr>
                    {% endif %}
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}



<!-- IMPORT Table JS -->
{% block javascript %}
<script src="/static/assets/js/datatables/jquery.dataTables.min.js"></script>
<script src="/static/assets/js/datatables/dataTables.bootstrap4.min.js"></script>
<script src="/static/assets/js/datatables/dataTables.responsive.js"></script>
<script>
  $(document).ready(function () {
    $('#dataTable').DataTable({
      responsive: true
    });
  });

  $(document).ready(function () {
    $('#dataTable1').DataTable({
      responsive: true
    });
  });
</script>
{% endblock %}

WEB/board/templates/board/detail.html
{% extends 'extend.html' %}
{% block main %}
<br>
<br>
<div class="main main-raised" style=text-align:center;>
    <div class="section">
        <div class="container">
            <h2>제목: {{board.title}}</h2>
            <p>글쓴이: {{board.writer}}</p>
            {% if board.image %}
            <img src="{{ board.image.url }}" alt="image" style="width: 600px; height:auto;">
            {% endif %}
            <p>내용: {{board.content}}</p>
        </div>
        {% for comment in board.comments.all %}
        <div class="card">
            <div class="alert card-body" style="margin-bottom: 0%">
                {{ comment.comment_text }}
                <a style="color: black;" href="{% url 'board:comment_delete' board.id comment.id %}" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span></a>
            </div>
          </div>
        {% endfor %}
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                {{ form }}
            </div>
            <input class="btn btn-primary" type="submit" value="댓글쓰기">
        </form>
    </div>
</div>
{% endblock %}

WEB/board/templates/board/edit.html
{% extends 'extend.html' %}
{% block main %}
<br><br>
<div class="main main-raised">
    <div class="section"> 
        <div class="container">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input class="btn btn-dark" type="submit" value="수정하기">
        </form>
        </div>
    </div>
</div>
{% endblock %}

WEB/board/templates/board/new.html
{% extends 'extend.html' %}
{% load crispy_forms_tags %}

{% block main %}
<div class="main main-raised">
    <div class="section section-contacts">
        <div class="row">
            <div class="col-md-8 ml-auto mr-auto">
                <h2 class="text-center title">NewBoard</h2>
                <h4 class="text-center description font">분실물이나 지하철내에서 일어나는 사건들에 대해 이야기하고 기록해보세요.</h4>
                <form class="contact-form" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form.title|as_crispy_field}}
                    </div>
                    <div class="row">
                        <div class="col-md-5">
                            <div class="form-group">
                                {{ form.stat|as_crispy_field }}
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="form-group">
                                {{ form.hashtags|as_crispy_field }}
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <i class="material-icons">add_photo_alternate</i>{{ form.image|as_crispy_field }}
                            </div>
                        </div>
                        
                    </div>
                    <div class="form-group">
                        {{ form.content|as_crispy_field }}
                    </div>
                    
                    <div class="row">
                        <div class="col-md-4 ml-auto mr-auto text-center">
                            <input class="btn btn-primary" type="submit" value="제출하기">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}