WEB/NawamMa/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "NawamMa"

urlpatterns = [
    path("", views.layout, name='home'),
    path("mypage/", views.mypage, name='mypage'),

    #만든이 소개
    path('maker/', views.maker , name ='maker'),
    path('extend/', views.extend , name ='extend'),
    #출발/목적지 입력
    path('start/', views.start, name = 'start'),
    path('startP/', views.startP, name = 'startP'),
    #지하철 혼잡도
    path('subway/', views.subway, name = 'subway'),
    path('subwayP/', views.subwayP, name = 'subwayP'),
    #좌석관련
    path('seat/<int:number>/', views.seat , name ='seat'),
    path('preRequset/', views.preRequset , name ='preRequset'),
    path('seatP/<int:number>/', views.seatP , name ='seatP'),
    path('MseatP/', views.MseatP, name = 'MseatP'),
    path('Mseat/', views.Mseat, name = 'Mseat'),
]

WEB/board/urls.py
from django.urls import path
from . import views

app_name = "board"

urlpatterns = [
    path("boardlist/", views.boardlist, name='boardlist'),
    path('create/', views.create, name='create'),
    path('newboard/', views.boardform, name='newboard'),
    path('edit/<int:pk>', views.edit, name='edit'),
    path('remove/<int:pk>', views.remove, name='remove'),
    path('detail/<int:pk>', views.detail, name='detail'),
    path('detail/<int:board_id>/<int:comment_id>', views.comment_delete, name='comment_delete'),
    ##모바일뷰
    path('Mboard/', views.Mboard , name ='Mboard'),
]

WEB/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("NawamMa.urls")),  #기존기능
    path('board/', include("board.urls")), #게시판
    path('member/', include("member.urls")), #기존로그인
    path('accounts/', include('allauth.urls')), #소셜로그인
    ]
    
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WEB/NawamMa/models.py
from django.db import models

# Create your models here.

WEB/NawamMa/views.py
from django.shortcuts import render, redirect
import serial
import json
from pprint import pprint
from board.models import Board
import board.views

## 지하철 API
# import urllib
# import json
# from pprint import pprint

def mypage(request):
        boards = Board.objects
        return render(request, 'NawamMa/mypage.html', {'boards':boards})

# 단순 소개페이지
def layout(request):
        return render(request, 'NawamMa/index.html')
def maker(request):
        return render(request, 'NawamMa/maker.html')
def extend(request):
        return render(request, 'NawamMa/extend.html')

## 일반자리 관련
def start(request):
        return render(request, 'NawamMa/start.html')

def subway(request):
        departure = request.GET['departure']
        destination = request.GET['destination']
        return render(request, 'NawamMa/subway.html', {'departure':departure, 'destination':destination})

def seat(request, number):
        ser = serial.Serial(
                port='COM4',
                baudrate=9600,
        )

        print('아두이노와 통신 시작')
        print('아두이노의 접속 포트는 COM4 입니다.\n')

        number = number

        while True:
                if ser.readable():
                        res = ser.readline()
                        json_data = json.loads(res.decode()[:-1])  ##json_data -> json으로 파싱된 데이터를 dict형태로 바뀌서 저장
                        print(json_data)
                        return render(request, 'NawamMa/seat.html', {'json_data': json_data, 'number':number})
        #if(val <= 0 )
                else:
                        print("연결을 실패했습니다.")
                        return render(request, 'NawamMa/seat.html') # front 테스트용 임시 return
        
def Mseat(request):
        ser = serial.Serial(
                port='COM4',
                baudrate=9600,
        )

        print('아두이노와 통신 시작')
        print('아두이노의 접속 포트는 COM4 입니다.\n')

        while True:
                if ser.readable():
                        res = ser.readline()
                        json_data = json.loads(res.decode()[:-1])  ##json_data -> json으로 파싱된 데이터를 dict형태로 바뀌서 저장
                        print(json_data)
                        return render(request, 'NawamMa/Mseat.html', {'json_data': json_data})
        #if(val <= 0 )
                else:
                        print("연결을 실패했습니다.")
                        return render(request, 'NawamMa/Mseat.html') # front 테스트용 임시 return



## 임산부자리 관련
def startP(request):
        return render(request, 'NawamMa/startP.html')

def subwayP(request):
        departure = request.GET['departure']
        destination = request.GET['destination']
        return render(request, 'NawamMa/subwayP.html', {'departure':departure, 'destination':destination})

def MseatP(request):
        ser = serial.Serial(
                port='COM4',
                baudrate=9600,
        )

        print('아두이노와 통신 시작')
        print('아두이노의 접속 포트는 COM4 입니다.\n')


        while True:
                if ser.readable():
                        res = ser.readline()
                        json_data = json.loads(res.decode()[:-1])  ##json_data -> json으로 파싱된 데이터를 dict형태로 바뀌서 저장
                        print(json_data)
                        return render(request, 'NawamMa/MseatP.html', {'json_data': json_data})
        # # if(val <= 0 )
                else:
                        print("연결을 실패했습니다.")
                        return redirect('/')
        


def seatP(request, number):
        ser = serial.Serial(
                        port='COM4',
                        baudrate=9600,
                )
        
        print('아두이노와 통신 시작')
        print('아두이노의 접속 포트는 COM4 입니다.\n')

        number = number
        while True:
                if ser.readable():
                        res = ser.readline()
                        json_data = json.loads(res.decode()[:-1])  ##json_data -> json으로 파싱된 데이터를 dict형태로 바뀌서 저장
                        print(json_data)
                        return render(request, 'NawamMa/seatP.html', {'json_data': json_data, 'number':number})
        # # if(val <= 0 )
                else:
                        print("연결을 실패했습니다.")
                        return redirect('/')

# 임산부가 요청보낼 시 아두이노 불과 소리 나오게하는 url
def preRequset(request):
        ser = serial.Serial(
                port='COM4',
                baudrate=9600,
        )

        print('아두이노와 통신 시작')
        print('아두이노의 접속 포트는 COM6 입니다.\n')

        while True:
                c = 'p'
                c = c.encode()
                ser.write(c)
                print(c)

                if ser.readable():
                        stop = ser.readline()
                        stopA = stop.decode()
                        stopB = stopA.strip()
                        print(stopB)
                        if stopB == 'T':
                                #return render(request, 'NawamMa/seatP.html')
                                return redirect('/')

# ### 지하철 API 사용
# ServiceKey = "6369785570726c613235676b55494f"

# # if 문을 사용해서 요청에 따라 다른 url을 호출하도록한다. (API)
# # + dict을 다른 페이지에 보내도록한다. 각 보여주는 페이지를 따로 만들어야할듯?

# url = "http://swopenapi.seoul.go.kr/api/subway/" + ServiceKey + "/json/firstLastTimetable/0/10/%EC%98%A8%EC%88%98"

# request = urllib.request.Request(url)
# response = urllib.request.urlopen(request)
# rescode = response.getcode()
# if(rescode==200):
#     response_body = response.read()
#     print(response_body.decode('utf-8'))
#     dict = json.loads(response_body.decode('utf-8'))
#     pprint(dict)
# else:
#     print("Error Code:" + rescode)

##원리 -> url호출시 json 방식으로 요청한 정보를 보여줌 -> dict객체에 json의 값들을 저장함 -> dict을 하나하나 나눠서 출력해주면 완벽크

WEB/NawamMa/templates/NawamMa/MseatP.html
{% extends 'extend.html' %}

{% block main %}
<div class="main main-raised">
    <div class="section text-center">
        <div class="container">
            <div class="row">
                <div class="col-md-6 ml-auto mr-auto">
                    <div class="profile-tabs">
                        <ul class="nav nav-pills nav-pills-primary nav-pills-icons justify-content-center"
                            role="tablist">

                            <li class="nav-item">
                                <a class="nav-link" href="#seat" data-toggle="tab">
                                    <i class="material-icons">tram</i> 좌석배치도
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="card-body ">
                <div class="tab-content text-center">

                    <div class="tab-pane active" id="seat">

                        <!-- 새로고침 버튼 -->
                        <a onClick="window.location.reload()" class="btn btn-primary btn-fab btn-link">
                            <i class="material-icons">autorenew</i>
                        </a>

                        <!-- 세로형 좌석배치 -->
                        <div class="d-flex justify-content-around">
                            <button class="btn btn-success btn-fab btn-link">
                                <i class="material-icons">event_seat</i>
                            </button>
                            <button class="btn btn-success btn-fab btn-link">
                                <i class="material-icons">event_seat</i>
                            </button>
                        </div>
                        <div class="d-flex justify-content-around">
                            <button class="btn btn-success btn-fab">
                                <i class="material-icons">event_seat</i>
                            </button>
                            {% if json_data.seat == '0' %}
                            <button class="btn btn-success btn-fab btn-link">
                                <i class="material-icons">event_seat</i>
                            </button>
                            {% else %}
                            <button class="btn btn-success btn-fab">
                                <i class="material-icons">event_seat</i>
                            </button>
                            {% endif %}
                            
                        </div>
                        <div class="d-flex justify-content-around">
                            <button class="btn btn-success btn-fab btn-link">
                                <i class="material-icons">event_seat</i>
                            </button>
                            <button class="btn btn-success btn-fab">
                                <i class="material-icons">event_seat</i>
                            </button>
                        </div>

                        <div class="d-flex justify-content-around">
                            <button class="btn btn-default btn-fab btn-link">
                                <i class="material-icons">play_for_work</i>
                            </button>
                            <button class="btn btn-default btn-fab btn-link">
                                <i class="material-icons">play_for_work</i>
                            </button>
                        </div>

                        <div class="d-flex justify-content-around">

                            <a href="{% url 'NawamMa:preRequset' %}" class="btn btn-danger btn-fab"
                                data-toggle="tooltip" data-placement="right" title="자리요청">
                                <i class="material-icons">event_seat</i>
                            </a>

                            {% if json_data.seat2 == '0' %}
                            <a href="{% url 'NawamMa:preRequset' %}" class="btn btn-danger btn-fab btn-link"
                                data-toggle="tooltip" data-placement="right" title="자리요청">
                                <i class="material-icons">event_seat</i>
                            </a>
                            {% else %}
                            <a href="{% url 'NawamMa:preRequset' %}" class="btn btn-danger btn-fab"
                                data-toggle="tooltip" data-placement="right" title="자리요청">
                                <i class="material-icons">event_seat</i>
                            </a>
                            {% endif %}

                        </div>
                        <div class="d-flex justify-content-around">
                            <button class="btn btn-info btn-fab btn-link">
                                <i class="material-icons">event_seat</i>
                            </button>
                            <button class="btn btn-info btn-fab">
                                <i class="material-icons">event_seat</i>
                            </button>
                        </div>
                        <div class="d-flex justify-content-around">
                            <button class="btn btn-info btn-fab">
                                <i class="material-icons">event_seat</i>
                            </button>
                            <button class="btn btn-info btn-fab">
                                <i class="material-icons">event_seat</i>
                            </button>
                        </div>
                        <div class="d-flex justify-content-around">
                            <button class="btn btn-info btn-fab">
                                <i class="material-icons">event_seat</i>
                            </button>
                            {% if json_data.seat3 == '0' %}
                                <button class="btn btn-info btn-fab btn-link">
                                    <i class="material-icons">event_seat</i>
                                </button>
                                {% else %}
                                <button class="btn btn-info btn-fab">
                                    <i class="material-icons">event_seat</i>
                                </button>
                                {% endif %}
                        </div>

                        <div class="d-flex justify-content-around">
                            <button class="btn btn-info btn-fab">
                                <i class="material-icons">event_seat</i>
                            </button>
                            <button class="btn btn-info btn-fab">
                                <i class="material-icons">event_seat</i>
                            </button>
                        </div>
                        <div class="d-flex justify-content-around">
                            <button class="btn btn-info btn-fab">
                                <i class="material-icons">event_seat</i>
                            </button>
                            {% if json_data.seat4 == '0' %}
                                <button class="btn btn-info btn-fab btn-link">
                                    <i class="material-icons">event_seat</i>
                                </button>
                            {% else %}
                                <button class="btn btn-info btn-fab">
                                    <i class="material-icons">event_seat</i>
                                </button>
                            {% endif %}
                        </div>
                        <div class="d-flex justify-content-around">
                            <a href="{% url 'NawamMa:preRequset' %}" class="btn btn-danger btn-fab btn-link"
                                data-toggle="tooltip" data-placement="right" title="자리요청">
                                <i class="material-icons">event_seat</i>
                            </a>
                            <a href="{% url 'NawamMa:preRequset' %}" class="btn btn-danger btn-fab"
                                data-toggle="tooltip" data-placement="right" title="자리요청">
                                <i class="material-icons">event_seat</i>
                            </a>
                        </div>

                        <div class="d-flex justify-content-around">
                            <button class="btn btn-default btn-fab btn-link">
                                <i class="material-icons">play_for_work</i>
                            </button>
                            <button class="btn btn-default btn-fab btn-link">
                                <i class="material-icons">play_for_work</i>
                            </button>
                        </div>

                        <div class="d-flex justify-content-around">
                            <button class="btn btn-success btn-fab">
                                <i class="material-icons">event_seat</i>
                            </button>
                            <button class="btn btn-success btn-fab">
                                <i class="material-icons">event_seat</i>
                            </button>
                        </div>
                        <div class="d-flex justify-content-around">
                            <button class="btn btn-success btn-fab btn-link">
                                <i class="material-icons">event_seat</i>
                            </button>
                            <button class="btn btn-success btn-fab">
                                <i class="material-icons">event_seat</i>
                            </button>
                        </div>
                        <div class="d-flex justify-content-around">
                            <button class="btn btn-success btn-fab">
                                <i class="material-icons">event_seat</i>
                            </button>
                            <button class="btn btn-success btn-fab">
                                <i class="material-icons">event_seat</i>
                            </button>
                        </div>
                        <!-- 세로형 좌석배치 -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

WEB/NawamMa/templates/NawamMa/extend.html
{% extends 'extend.html' %}

{% block main %}
{% endblock %}

WEB/NawamMa/templates/NawamMa/index.html
{% extends 'index.html' %}

WEB/NawamMa/templates/NawamMa/mypage.html
{% extends 'extend.html' %}

{% block main %}

<div class="main main-raised">
    <div class="section">
        <div class="container center">
            <h1 class="font"> {{user.nickname}}'s MyPage</h1>
            <br>
            <div style="margin-right: auto; margin-left: auto;">
                <div class="row">
                    <div class="col-xs-6 col-sm-3">
                        <i class="material-icons material-icons1">face</i>
                        <h3 class="font">Nickname: <br>{{user.nickname}}</h3>
                    </div>
                    <div class="col-xs-6 col-sm-3">
                        <i class="material-icons material-icons1">mail</i>
                        <h3 class="font">Email: {{user.email}}</h3>
                    </div>
                    <div class="col-xs-6 col-sm-3">
                        <i class="material-icons material-icons1">cake</i>
                        <h3 class="font">Birthday: <br>{{user.birth}}</h3>
                    </div>
                    <div class="col-xs-6 col-sm-3">
                        <i class="material-icons material-icons1">phone</i>
                        <h3 class="font">PhoneNumber: <br>{{user.cellphone}}</h3>
                    </div>
                </div>
            </div>
            <br><br>
            <h2 class="font">당신이 작성한 게시글</h2>
            <div class="row">
                {% for board in boards.all %}
                {% if board.writer == user.nickname %}
                <div class="col-sm-4 col-md-4 container">
                    <a class="card" style="background-color: #DAD9FF; " href="{% url 'board:detail' pk=board.pk %}">

                        <h3 class="font" style="text-align: center;">{{board.title}}</h3>
                        <hr>
                        <div class="container">
                            <p> 날짜: {{board.date}}</p>
                            <p> 내용: {{board.summary}}</p>
                        </div>
                        <a href="{% url 'board:remove' pk=board.pk %}" class="btn btn-danger btn-circle">
                            <i class="fa fa-trash"></i>
                        </a>
                        <a href="{% url 'board:edit' pk=board.pk %}" class="btn btn-success btn-circle">
                            <i class="fa fa-check"></i>
                        </a>

                    </a>
                </div>
                {% endif %}
                {% endfor %}

            </div>
        </div>
    </div>
</div>

{% endblock %}

WEB/NawamMa/templates/NawamMa/seatP.html
{% extends 'extend.html' %}

{% block main %}
<div class="main main-raised">
    <div class="section text-center">
        <div class="container">
            <!-- ----------- 테스트 ---------------- -->
            {% if json_data.seat == '0' %}
            <!-- 빈자리일 경우 -->
            <button class="btn btn-success btn-fab btn-link">
                <i class="material-icons">event_seat</i>
            </button>
            {% else %}
            <button class="btn btn-success btn-fab">
                <i class="material-icons">event_seat</i>
            </button>
            {% endif %}
            <!-- ----------- 테스트 ---------------- -->

            <!-- 가로형 좌석배치 -->
            <button class="btn btn-success btn-fab btn-link">
                <i class="material-icons">event_seat</i>
            </button>
            {% if json_data.seat == '0' %}
            <!-- 빈자리일 경우 -->
            <button class="btn btn-success btn-fab btn-link">
                <i class="material-icons">event_seat</i>
            </button>
            {% else %}
            <button class="btn btn-success btn-fab">
                <i class="material-icons">event_seat</i>
            </button>
            {% endif %}

            <button class="btn btn-default btn-fab btn-link">
                <i class="material-icons">play_for_work</i>
            </button>

            {% if json_data.seat2 == '0' %}
            <!-- 빈자리일 경우 -->
            <a href="{% url 'NawamMa:preRequset' %}" class="btn btn-danger btn-fab btn-link seat" data-toggle="tooltip"
                data-placement="bottom" title="자리요청">
                <i class="material-icons">event_seat</i>
            </a>
            {% else %}
            <a href="{% url 'NawamMa:preRequset' %}" class="btn btn-danger btn-fab seat" data-toggle="tooltip"
                data-placement="bottom" title="자리요청">
                <i class="material-icons">event_seat</i>
            </a>
            {% endif %}

            
            <button class="btn btn-info btn-fab">
                <i class="material-icons">event_seat</i>
            </button>
            <button class="btn btn-info btn-fab">
                <i class="material-icons">event_seat</i>
            </button>
            {% if json_data.seat3 == '0' %}
            <!-- 빈자리일 경우 -->
            <button class="btn btn-info btn-fab btn-link">
                <i class="material-icons">event_seat</i>
            </button>
            {% else %}
            <button class="btn btn-info btn-fab">
                <i class="material-icons">event_seat</i>
            </button>
            {% endif %}
            <button class="btn btn-info btn-fab">
                <i class="material-icons">event_seat</i>
            </button>
            {% if json_data.seat4 == '0' %}
            <!-- 빈자리일 경우 -->
            <button class="btn btn-info btn-fab btn-link">
                <i class="material-icons">event_seat</i>
            </button>
            {% else %}
            <button class="btn btn-info btn-fab">
                <i class="material-icons">event_seat</i>
            </button>
            {% endif %}
            <a href="{% url 'NawamMa:preRequset' %}" class="btn btn-danger btn-fab btn-link" data-toggle="tooltip"
                data-placement="bottom" title="자리요청">
                <i class="material-icons">event_seat</i>
            </a>

            <button class="btn btn-default btn-fab btn-link">
                <i class="material-icons">play_for_work</i>
            </button>

            <button class="btn btn-success btn-fab">
                <i class="material-icons">event_seat</i>
            </button>
            <button class="btn btn-success btn-fab">
                <i class="material-icons">event_seat</i>
            </button>
            <button class="btn btn-success btn-fab btn-link">
                <i class="material-icons">event_seat</i>
            </button>


            <br>
            <br>
            <h2 class="font"><b>{{ number }}</b>번 칸</h2>
            <br>
            <br>

            <button class="btn btn-success btn-fab">
                <i class="material-icons">event_seat</i>
            </button>
            <button class="btn btn-success btn-fab">
                <i class="material-icons">event_seat</i>
            </button>
            <button class="btn btn-success btn-fab">
                <i class="material-icons">event_seat</i>
            </button>

            <button class="btn btn-default btn-fab btn-link">
                <i class="material-icons">play_for_work</i>
            </button>

            <a href="{% url 'NawamMa:preRequset' %}" class="btn btn-danger btn-fab" data-toggle="tooltip"
                data-placement="top" title="자리요청">
                <i class="material-icons">event_seat</i>
            </a>
            <button class="btn btn-default btn-fab">
                <i class="material-icons">event_seat</i>
            </button>
            <button class="btn btn-default btn-fab">
                <i class="material-icons">event_seat</i>
            </button>
            <button class="btn btn-default btn-fab btn-link">
                <i class="material-icons">event_seat</i>
            </button>
            <button class="btn btn-default btn-fab">
                <i class="material-icons">event_seat</i>
            </button>
            <button class="btn btn-default btn-fab">
                <i class="material-icons">event_seat</i>
            </button>
            <a href="{% url 'NawamMa:preRequset' %}" class="btn btn-danger btn-fab" data-toggle="tooltip"
                data-placement="top" title="자리요청">
                <i class="material-icons">event_seat</i>
            </a>

            <button class="btn btn-default btn-fab">
                <i class="material-icons">play_for_work</i>
            </button>

            <button class="btn btn-success btn-fab btn-link">
                <i class="material-icons">event_seat</i>
            </button>
            <button class="btn btn-success btn-fab btn-link">
                <i class="material-icons">event_seat</i>
            </button>
            <button class="btn btn-success btn-fab">
                <i class="material-icons">event_seat</i>
            </button>
        </div>
    </div>
</div>
{% endblock %}

WEB/NawamMa/templates/NawamMa/start.html
{% extends 'extend.html' %}

{% block main %}
<div class="main main-raised">
    <div class="section text-center">
        <div class="container">
            <h2 class="font">출발지와 목적지를 입력하세요.</h2>
            <div class="row">
                <div class="col-md-6">
                    <img src="/static/assets/img/linemap.svg" width="85%" height="85%" />
                </div>
                <div class="col-md-6">
                    <br><br><br><br>
                    <form action="{% url 'NawamMa:subway' %}" method="get">
                        출발지 : <input class="form-group" type="text" name="departure"><br>
                        목적지 : <input class="form-group" type="text" name="destination"><br>
                        <input class="btn btn-primary" type="submit" value="검색하기">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

WEB/NawamMa/templates/NawamMa/startP.html
{% extends 'extend.html' %}

{% block main %}
<div class="main main-raised">
    <div class="section text-center">
        <div class="container">
            <h2 class="font">출발지와 목적지를 입력하세요.</h2>
            <div class="row">
                <div class="col-md-6">
                    <img src="/static/assets/img/linemap.svg" width="85%" height="85%" />
                </div>
                <div class="col-md-6">
                    <br><br><br><br>
                    <form action="{% url 'NawamMa:subwayP' %}" method="get">
                        출발지 : <input class="form-group" type="text" name="departure"><br>
                        목적지 : <input class="form-group" type="text" name="destination"><br>
                        <input class="btn btn-primary" type="submit" value="검색하기">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

WEB/NawamMa/templates/NawamMa/subway.html
{% extends 'extend.html' %}

{% block main %}
<div class="main main-raised">
    <div class="section text-center">
        <div class="container">
            <h2 class="font"><b>{{ departure }}</b>에서 <b>{{ destination }}</b>까지 가는 열차의 혼잡도입니다.</h2>
            <div class="row">
                <div class="col-sm-3">
                    <a class="btn btn-success btn-round" href="{% url 'NawamMa:seat' number=1 %}">1번 칸<br>
                    <img src="/static/assets/img/혼잡도/empty.png" width="70%" height="70%" /></a>
                </div>
                <div class="col-sm-3">
                    <a class="btn btn-danger btn-round" href="{% url 'NawamMa:seat' number=2 %}">2번 칸<br>
                    <img src="/static/assets/img/혼잡도/full.png" width="70%" height="70%" /></a>
                </div>
                <div class="col-sm-3">
                    <a class="btn btn-warning btn-round" href="{% url 'NawamMa:seat' number=3 %}">3번 칸<br>
                    <img src="/static/assets/img/혼잡도/soso.png" width="70%" height="70%" /></a>
                </div>
                <div class="col-sm-3">
                    <a class="btn btn-success btn-round" href="{% url 'NawamMa:seat' number=4 %}">4번 칸<br>
                    <img src="/static/assets/img/혼잡도/empty.png" width="70%" height="70%" /></a>
                </div>
                <div class="col-sm-3">
                    <a class="btn btn-warning btn-round" href="{% url 'NawamMa:seat' number=5 %}">5번 칸<br>
                    <img src="/static/assets/img/혼잡도/soso.png" width="70%" height="70%" /></a>
                </div>
                <div class="col-sm-3">
                    <a class="btn btn-success btn-round" href="{% url 'NawamMa:seat' number=6 %}">6번 칸<br>
                    <img src="/static/assets/img/혼잡도/empty.png" width="70%" height="70%" /></a>
                </div>
                <div class="col-sm-3">
                    <a class="btn btn-warning btn-round" href="{% url 'NawamMa:seat' number=7 %}">7번 칸<br>
                    <img src="/static/assets/img/혼잡도/soso.png" width="70%" height="70%" /></a>
                </div>
                <div class="col-sm-3">
                    <a class="btn btn-danger btn-round" href="{% url 'NawamMa:seat' number=8 %}">8번 칸<br>
                    <img src="/static/assets/img/혼잡도/full.png" width="70%" height="70%" /></a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}